#!/usr/bin/bash
gnuplot -e "filename='fb_cov.dat'" foo.plg
ipfile=$1
reset
set terminal png
set output "plot.png"
set ylabel "Coverage"
set xlabel "Time" 
set grid 

plot "fb_cov.dat" using 1:2 with lines title 'Frontier Approach' 
